### ISSUE TITLE
Can I use two Uno CNC shields instead of building the Thor-specific PCB?

### ISSUE THREAD

**Issue by DanielYWoo** [AngelLM/Thor#100]
I did not try yet but I think this is possible, right? if so it saves a whole lot of time to mill the PCB with a CNC

**Comment by AngelLM** [comment]
Hello Daniel,

Yes, it should be possible, as common Uno CNC shields are capable of controlling up to 4 stepper motors.
Back in time, I did something similar using 2 RAMPS Shields.
You just have to keep in mind, that when sending the degrees of motion to the joints, you will have to split the communication into 2 parts. Probably one for the first 3 joints and one for the last 3.

Anyway, before you think about machining the PCB, take a look at the [Thor Control PCB](https://github.com/AngelLM/ThorControlPCB). You can order it from PCB manufacturers ([PCBWay](https://www.pcbway.com/project/shareproject/Thor_ControlPCB.html) for example) and it doesn't cost much money, the only thing is that you will have to solder the components yourself.

**Comment by DanielYWoo** [comment]
Thanks, you are an angel. Will try!
