### ISSUE TITLE
Cooper plate?

### ISSUE THREAD

**Issue by i-make-robots** [AngelLM/Thor#41]
In bill of materials

**Comment by AngelLM** [comment]
Hi! The cooper plate is needed if you make the first version of Control PCB. 
I'll upload it soon with the materials of the new version of the Control PCB :)

Regards!

**Comment by i-make-robots** [comment]
I get it. Should be spelled "copper".

**Comment by AngelLM** [comment]
Fixed on commit 4d9601d
Thanks for the correction!
