### ISSUE TITLE
Art 4 Transmission Column unnecessarily tight fit for bearing

### ISSUE THREAD

**Issue by b-adkins** [AngelLM/Thor#52]
The smallest extra print material will mean the bearing does not fit down the central shaft and can be damaged by inexperienced makers trying to force it. Instead of a single inner radius that is the exact radius of the bearing, there could be a loose fit for almost all the shaft except the final place where the bearing would continue to fit snugly. As there is a screw holding the bearing in, there is no danger of the bearing falling out.

**Comment by AngelLM** [comment]
Hi @b-adkins ,
I think I don't get the point of your idea, could you add a diagram or something like that to help me to understand it? 
Thanks! 😄
