### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ArtoriastheAbyssWalker** [AngelLM/Thor#63]
I can not download all the documents, can you help me?

**Comment by AngelLM** [comment]
Hi @ArtoriastheAbyssWalker 
Have you tried to click on "Clone or download" green button and then click on "Download Zip" option?
If you have intalled git in your PC and you want to download the repo using git tool you can also type the following code in your terminal/git terminal:
`git clone https://github.com/AngelLM/Thor`

Hope it helps!
