### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by wilsoc5** [AngelLM/Thor#70]
The readme says the files in this repo are licenses by a CC-BA-SA (Creative Commons Attribution-ShareAlike 4.0 International License). However, the license file says it is GPL2. So... Which is the latest version licensed under?

**Comment by AngelLM** [comment]
Since the first commit I said that all the files included in the repository are licensed under CC-BY-SA 4.0 License. The LICENSE file was wrong, I just fixed it!
Thank you very much for noticing! 😄
