### ISSUE TITLE
Current software to use

### ISSUE THREAD

**Issue by LoLo2207** [AngelLM/Thor#74]
Hi, I have an Ultratronics Pro board but I don't know what firmware to use. Is there any firmware available for this board?

If there isn't, what board can I use to easily wire and control the arm besides the custom PCB?

**Comment by DavidVives** [comment]
Dear LoLo2207, did you find any board and firmware that works?
Many thanks and best regards

**Comment by AngelLM** [comment]
As far as I know, currently there is no other option than Arduino Mega + [ThorControlPCB](https://github.com/AngelLM/ThorControlPCB/) with the [GRBL Thor version](https://github.com/AngelLM/grbl)
