### ISSUE TITLE
Modificar Asgard

### ISSUE THREAD

**Issue by lisergio** [AngelLM/Thor#81]
Buenas de nuevo!!!
Después de mucho tiempo, he retomado el proyecto... y he pensado usar  una raspberry pi con pantalla táctil para controlar a thor, pero al instalar asgard en la raspberry, resulta que no cabe en la pantalla, que tiene una resolución máxima de 800x400..
Hay alguna manera sencilla de modificar el gui.py para poner solo lo básico? 
El botón de conectar, y los sliders de las articulaciones, y de paso, eliminar el boton “go” y que envie el gcode directamente al mover el slider... 
gracias!!!!

**Comment by AngelLM** [comment]
Hi! The development of Asgard is being made in its own repo: https://github.com/AngelLM/Asgard
I'm gonna close this issue, but I have taken note of this for future designs.

Thanks! :)
