### ISSUE TITLE
5mm (diameter) rods do not fit on 625ZZ bearings and similar issue with motor shaft and pulley

### ISSUE THREAD

**Issue by emlachapelle** [AngelLM/Thor#84]
In the process of building Thor I've run into the issue that the 5mm (diameter) rods do not fit in the 625ZZ bearings that were on the bill of material... Similarly, the GT2-6 Timing Belt Pulley 20T (inner bore of 5mm) does not fit at all on the shaft of the Stepper Motor 17HS13-0404S-PG5 also provided in the bill of material. 

Would it be possible to know what you used instead of these components to ensure a proper fit? Thanks!

**Comment by AngelLM** [comment]
It should fit as the inner bore has 5mm diameter... I used some spare threaded M5 rods that I had at home in case it helps you.
About the Pulley issue, has your motor a 5mm diameter shaft? I don´t know why but there are models named the same with 6mm diameter shaft. In case it is and still doesn´t fit all I can recommend is to file the inner bore of the pulley a bit, or make the hole bigger with a drill
