### ISSUE TITLE
Notes/feedback about FreeCAD used within collaborative projects like Thor

### ISSUE THREAD

**Issue by luzpaz** [AngelLM/Thor#89]
It would be helpful to understand what are some of the workflows that this collaborative project is encountering while using FreeCAD. Anything from positives, negatives/bugs, and feature requests (that would make collaboration more optimized) etc...

Please notate this ticket. Eventually these notes can be reported back to the FreeCAD community.

**Comment by AngelLM** [comment]
Hi @luzpaz !

Sadly, I don't remember receiving any pull request with changes or contribution of FreeCAD files. 
Some users made new pieces or modifications from the STP files using other CAD software and I have migrated it to FreeCAD afterwards.

Hope it helps!

**Comment by luzpaz** [comment]
Thanks!
